-- Wildberries DBS orders come through the same corridor as printed WB cards but
-- are generated by the courier-delivery gate, so they need their own source for
-- operator filtering and accounting.
--
-- Additive only: no existing row changes, and PostgreSQL 12+ allows ADD VALUE
-- inside the transaction Prisma wraps the migration in as long as the new value
-- is not referenced in that same transaction.
ALTER TYPE "OrderSource" ADD VALUE IF NOT EXISTS 'WB_DBS';
