// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function verifiedDatabaseUrl(raw: string) {
  try {
    const url = new URL(raw);
    if (url.searchParams.get("sslmode") === "require") url.searchParams.set("sslmode", "verify-full");
    return url.toString();
  } catch {
    return raw;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node ./prisma/seed.js",
  },
  datasource: {
    // We use process.env here to avoid throwing error during build
    // if the environment variable is not yet linked.
    url: verifiedDatabaseUrl(
      process.env.DATABASE_URL || "postgresql://johndoe:randompassword@localhost:5432/mydb",
    ),
  },
});
