// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node ./prisma/seed.js",
  },
  datasource: {
    // We use process.env here to avoid throwing error during build
    // if the environment variable is not yet linked.
    url: process.env.DATABASE_URL || "postgresql://johndoe:randompassword@localhost:5432/mydb",
  },
});
