-- AlterTable
ALTER TABLE "User" ADD COLUMN "bonusExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "rubleDiscount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "promoExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "promoSentAt" TIMESTAMP(3);
